"""
Django settings for personal_portfolio project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR2 = os.path.dirname(os.path.abspath(__file__))
# print ("\n\n os.path.abspath(__file__ = ",os.path.abspath(__file__))
# print ("\n os.path.dirname(os.path.abspath(__file__)) = ",os.path.dirname(os.path.abspath(__file__)))
# print("\n os.path.dirname(os.path.dirname(os.path.abspath(__file__))) =",os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# print ("BASE_DIR = ",BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "!^_6%0so9$a@u-w22nc56xcp0^spoo4k^3q!j016o5hll+#c#o"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','192.168.182.225','localhost']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "projects",
    "blog",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "personal_portfolio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["personal_portfolio/templates/"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "personal_portfolio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
#     }
# }

DATABASES_USER =os.getenv("PRJ1_DB_USER")
DATABASES_PASS =os.getenv("PRJ1_DB_PASS")
DATABASE_APPS_MAPPING = {'blog':'blogdb', 'projects':'projectsdb', 'app3':'db3', 'app4':'db4'}
DATABASE_ROUTERS = ['blog.router.CheckerRouter']
DATABASES_USER='psqladmin'
DATABASES_PASS='Ubub^6yhn'

print ("DATABASE_ROUTERS = ",DATABASE_ROUTERS)
print("DATABASES_USER = " ,DATABASES_USER)
print("DATABASES_PASS = ",DATABASES_PASS)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'personal_portfolio', 
        'USER': DATABASES_USER, 
        'PASSWORD': DATABASES_PASS,
        'HOST': '127.0.0.1', 
        'PORT': '5432',
    },
    'blogdb': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'personal_portfolio_blog', 
        'USER': DATABASES_USER, 
        'PASSWORD': DATABASES_PASS,
        'HOST': '127.0.0.1', 
        'PORT': '5432',
    },
    'projectsdb': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'personal_portfolio', 
        'USER': DATABASES_USER, 
        'PASSWORD': DATABASES_PASS,
        'HOST': '127.0.0.1', 
        'PORT': '5432',
    }

}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation"
        + ".UserAttributeSimilarityValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        + ".MinimumLengthValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        + ".CommonPasswordValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        + ".NumericPasswordValidator"
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = ( os.path.join(BASE_DIR,'static/'),os.path.join(BASE_DIR2,'static/'),)
# print ("\n\n************* STATICFILES_DIRS= ",STATICFILES_DIRS)